# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Jonah Marshall | Blog"
description: > # this means to ignore newlines until "email:"
   Welcome to my website, check out my thoughts on games I've played or look at some of the work I've done!

email: jonahmarshallyvr@gmail.com
#blog logo
logo: "/assets/images/icon.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/stanley_park.jpg"

name: 'Jonah Marshall'
author: 'Jonah Marshall'
author_image: "/assets/images/me.jpg"

paginate:	5

url: "http://www.jonahmarshall.cv/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
 
  - icon:	envelope
    url:	mailto:jonahmarshallyvr@gmail
    desc:	Send me an email
    share_url:
    share_title:
    share_link:

    
  - icon:	linkedin
    url:	https://www.linkedin.com/in/jonah-marshall-splash/
    desc:	Reach out on linkedin
    share_url:
    share_title:
    share_link:
    
  - icon:	file
    url:	assets/Jonah_Marshall_Resume.pdf
    desc:	Check out my CV
    share_url:
    share_title:
    share_link:
    

